version: '3'

volumes:
  mongo_data: {}
  traefik_acme: {}
  rabbitmq_data: {}
  postgres_data: {}

services:

  mongo:
    env_file: .env
    restart: always
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    env_file: .env
    restart: always
    image: rabbitmq:latest
    ports:
      - 5672
    volumes:
      - rabbitmq_data:/data

  redis:
    env_file: .env
    restart: always
    image: redis:latest
    ports:
      - 6379

  postgres:
    env_file: .env
    restart: always
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  worker: &worker
    env_file: .env
    restart: always
    build: backend  # Change this to your backend path. ed: ../my/backend/path
    command: celery -A myapp.tasks worker --loglevel=info
    links:
      - mongo:mongo
      - rabbitmq:rabbitmq
      - postgres:postgres
      - redis:redis

  backend:
    <<: *worker
    command: gunicorn autoapp:app -b :${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${BACKEND_DOMAIN}
      - traefik.frontend.rule=Host:${BACKEND_DOMAIN}

  socket:
    <<: *worker
    command: python sio_server.py ${SOCKET_PORT}
    expose:
      - ${SOCKET_PORT}
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${SOCKET_DOMAIN}
      - traefik.frontend.rule=Host:${SOCKET_DOMAIN}

  # This is ONLY for apps that nneds to support SSR.
  # If you don't use SSR, folow S3_FRONTEND_DEPLOYMENT.md to deploy directly on s3
  ssrfrontend:
    env_file: .env
    restart: always
    build: ssrfrontend  # Change this to your frontend path. ed: ../my/frontent/path
    command: PORT=${SSRFRONTEND_PORT} npm run serve:ssr
    expose:
      - ${SSRFRONTEND_PORT}
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${SSRFRONTEND_DOMAIN}
      - traefik.frontend.rule=Host:${SSRFRONTEND_DOMAIN}

  traefik:
    env_file: .env
    build: traefik
    depends_on:
      - backend
      - ssrfrontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_acme:/etc/traefik/acme/ # Defined in traefik/traefik.toml
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
